language: cpp
sudo: required

install:
  - curl http://ubuntu.openturns.org/openturns.org-repo.key | sudo apt-key add -
  - echo deb http://ubuntu.openturns.org precise main | sudo tee /etc/apt/sources.list.d/openturns.list
  - sudo apt-get update
  - sudo apt-get -y installtexlive-latex-recommended texlive-fonts-recommended texlive-latex-extra dvipng python-pip python-tk pandoc
  - sudo pip install jupyter matplotlib scikit-learn statsmodels numpy scipy logging decorator pytest numpydoc
  - wget http://ubuntu.openturns.org/pool/main/o/openturns/libopenturns0.9_1.8-1precise_amd64.deb
  - wget http://ubuntu.openturns.org/pool/main/o/openturns/python-openturns-dev_1.9~rc1-1precise_all.deb
  - sudo dpkg -i libopenturns0.9_1.8-1precise_amd64.deb
  - sudo dpkg -i python-openturns-dev_1.9~rc1-1precise_all.deb
# sphinx >=1.2 is looking better
  - git clone https://github.com/sphinx-doc/sphinx.git
  - pushd sphinx
  - python setup.py install --user
  - popd

script:
  - python setup.py install --user
  - py.test test/
  - cd ./doc/source/examples/ && jupyter-nbconvert --to rst *.ipynb
  - cd ../../ && make html