language: python

dist: trusty

install:
  - docker build -t otpod_docker_ot_18 .

script:
  - docker run -v $PWD:/var/otpod otpod_docker_ot_18 /bin/bash -c "cd /var/otpod && python setup.py install && pytest"
