language: python
sudo: required

python:
  - "2.7"
  - "3.4"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # add channel for openturns
  - conda config --add channels conda-forge
  # install dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION openturns jupyter matplotlib scikit-learn statsmodels numpy scipy decorator pytest numpydoc sphinx pandoc
  - source activate test-environment
  - python setup.py install

script:
  - python setup.py install
  - py.test test/